List<String> pakistanCities = [
  'Islamabad',
  'Karachi',
  'Lahore',
  'Rawalpindi',
  'Multan',
  'Faisalabad',
  'Peshawar',
  'Quetta',
  'Sialkot',
  'Gujranwala',
  'Hyderabad',
  'Sukkur',
  'Bahawalpur',
  'Mardan',
  'Abbottabad',
  'Gujrat',
  'Dera Ghazi Khan',
  'Sheikhupura',
  'Sargodha',
  'Mirpur Khas',
  'Jhelum',
  'Chiniot',
  'Kasur',
  'Rahim Yar Khan',
  'Okara',
  'Muzaffargarh',
  'Turbat',
  'Swat',
  'Zhob',
  'Kotli',
  'Bannu',
  'Chakwal',
  'Khuzdar',
  'Larkana',
  'Sahiwal',
  'Bhakkar',
  'Pakpattan',
  'Mianwali',
  'Nawabshah',
  'Chitral',
  'Haripur',
  'Mansehra',
  'Jhang',
  'Toba Tek Singh',
  'Narowal',
  'Nowshera',
  'Dera Ismail Khan',
  'Kohat',
  'Fateh Jang',
  'Ghotki',
  'Khanewal',
  'Shikarpur',
  'Swabi',
  'Chilas',
  'Bajaur',
  'Kohistan',
  'Batagram',
  'Hangu',
  'Karak',
  'Mingora',
  'Skardu',
  'Wazirabad',
  'Layyah',
  'Jampur',
  'Bhalwal',
  'Daska',
  'Jauharabad',
  'Pishin',
  'Tank',
  'Sadiqabad',
  'Buner',
  'Khairpur',
  'Dadu',
  'Badin',
  'Muzaffarabad',
  'Gulistan',
  'Pishin',
  'Jamalpur',
  'Layyah',
  'Bannu',
  'Dera Ghazi Khan',
  'Chakdara',
  'Shahran',
  'Khairpur',
  'Mushkabad'
];

List<String> pakistanProvinces = [
  'Punjab',
  'Sindh',
  'Khyber Pakhtunkhwa (KPK)',
  'Balochistan',
  'Azad Jammu & Kashmir (AJK)',
  'Gilgit-Baltistan (GB)',
  'Islamabad Capital Territory',
  'Not Registered'
];

List<String> vehicleRegistrationYears = [
  '2025',
  '2024',
  '2023',
  '2022',
  '2021',
  '2020',
  '2019',
  '2018',
  '2017',
  '2016',
  '2015',
  '2014',
  '2013',
  '2012',
  '2011',
  '2010',
  '2009',
  '2008',
  '2007',
  '2006',
  '2005',
  '2004',
  '2003',
  '2002',
  '2001',
  '2000',
  '1999',
  '1998',
  '1997',
  '1996',
  '1995',
  '1994',
  '1993',
  '1992',
  '1991',
  '1990',
  '1989',
  '1988',
  '1987',
  '1986',
  '1985',
  '1984',
  '1983',
  '1982',
  '1981',
  '1980',
  '1979',
  '1978',
  '1977',
  '1976',
  '1975',
  '1974',
  '1973',
  '1972',
  '1971',
  '1970',
  '1969',
  '1968',
  '1967',
  '1966',
  '1965',
  '1964',
  '1963',
  '1962',
  '1961',
  '1960',
  '1959',
  '1958',
  '1957',
  '1956',
  '1955',
  '1954',
  '1953',
  '1952',
  '1951',
  '1950',
  '1949',
  '1948',
  '1947',
];

List<String> carMakes = [
  "Suzuki",
  "Honda",
  "Toyota",
  "Kia",
  "Hyundai",
  "Changan",
  "MG",
  "Proton",
  "DFSK",
  "Audi",
  "BMW",
  "Mercedes-Benz",
  "Land Rover",
  "Nissan"
];

List<String> carModels = [
  "Honda Civic",
  "Honda City",
  "Honda BR-V",
  "Honda HR-V",
  "Toyota Corolla",
  "Toyota Yaris",
  "Toyota Fortuner",
  "Toyota Hilux",
  "Kia Sportage",
  "Kia Picanto",
  "Kia Sorento",
  "Hyundai Elantra",
  "Hyundai Tucson",
  "Hyundai Sonata",
  "Changan Alsvin",
  "Changan Karvaan",
  "MG HS",
  "MG ZS",
  "Proton X70",
  "Proton Saga",
  "DFSK Glory 580",
  "DFSK Mini Truck",
  "Audi A3",
  "Audi A4",
  "Audi Q5",
  "BMW 3 Series",
  "BMW X5",
  "BMW 5 Series",
  "Mercedes-Benz C-Class",
  "E-Class",
  "GLC",
  "Land Rover Defender",
  "Range Rover",
  "Range Rover Sport",
  "Nissan Altima",
  "Nissan Juke",
  "Nissan Leaf"
];

// 'Used Truck': [
//   'Cargo Landing Truck',
//   'Automatic',
//   'Concrete Mixer Truck',
//   'Flatbed Truck',
//   'Tailer Truck',
//   'Tanker Truck',
//   'Container Carrier Truck',
//   'Box Truck',
//   'Dumper Truck',
//   'Container Carrier',
//   'Freezer Truck',
//   'Dump Truck',
//   'Mazda Body Truck',
//   'Container Mini Truck',
//   'Oil Tanker Mini Truck',
//   'Poultry Truck',
//   'Mini Dumper Truck',
// ],

var categoriesList = {
  'Used Truck': [
    'Cargo Loading Truck',
    'Dumper Truck',
    'Mixer Truck',
    'Flatbed Cement Truck',
    'Trailer Machine',
    'Tanker Truck',
    'Container Truck',
    'Freezer Truck',
    'Mazda Body Truck',
    'Automatic Transmission Truck',
    'Oil Tanker Mini Truck',
    'Poultry Truck',
  ],
  'Used Bus': [
    'Nazai Express',
    'Daewo Express',
  ],
  'Machinery': [
    'Excavator Operator',
    'Loader Operator',
    'Roller Machine',
    'Grader Truck',
    'Mini Crane Machine',
    'Wheel Tractor',
    'Road Cutter',
    'Drilling Machine',
    'Compactor Machine',
    'Foklift Operator',
    'Buildozer',
    'Screening machine',
    'Crusher',
    'Conveyor',
    'Tractor',
    'Threshers',
    'Harvesters',
    'Seeders',
    'Plows'
  ],
};

var categoriesListForFilter = {
  'Used Truck': [
    'Cargo Landing Truck',
    'Automatic',
    'Concrete Mixer Truck',
    'Flatbed Truck',
    'Tailer Truck',
    'Tanker Truck',
    'Container Carrier Truck',
    'Box Truck',
    'Dumper Truck',
    'Container Carrier',
    'Freezer Truck',
    'Dump Truck',
    'Mazda Body Truck',
    'Container Mini Truck',
    'Oil Tanker Mini Truck',
    'Poultry Truck',
    'Mini Dumper Truck',
  ],
  'Used Bus': [
    'Nazai Express',
    'Daewo Express',
  ],
  'Auto parts': [
    'Body Parts',
    'Crush plant',
    'Hydraulic pump',
    'Cabin',
    'Hydraulic Jack',
    'Excavator',
    'Engine',
    'Loader Bucket',
    'Boozer Compressor',
  ],
  'Machinery': [
    'Excavator Operator',
    'Loader Operator',
    'Roller Machine',
    'Grader Truck',
    'Mini Crane Machine',
    'Wheel Tractor',
    'Road Cutter',
    'Drilling Machine',
    'Compactor Machine',
    'Foklift Operator',
    'Buildozer',
    'Screening machine',
    'Crusher',
    'Conveyor',
    'Tractor',
    'Threshers',
    'Harvesters',
    'Seeders',
    'Plows'
  ],
};

final List<String> truckEngines = [
  'Diesel Engine',
  'Petrol Engine',
  'CNG Engine',
  'LPG Engine',
  'Electric Engine',
  'Hybrid Engine',
  'Turbocharged Diesel Engine',
  'Natural Gas Engine',
  'Biofuel Engine',
];

final List<String> truckCapacities = [
  '1 Ton',
  '2 Ton',
  '3 Ton',
  '5 Ton',
  '7 Ton',
  '10 Ton',
  '12 Ton',
  '15 Ton',
  '20 Ton',
  '30 Ton',
  '40 Ton',
  '50 Ton',
];

final List<String> truckMileages = [
  '5 km/l',
  '6 km/l',
  '7 km/l',
  '8 km/l',
  '9 km/l',
  '10 km/l',
  '12 km/l',
  '15 km/l',
  '18 km/l',
  '20 km/l',
];

final List<String> truckAssembly = [
  'Imported',
  'Local',
];

final List<String> truckFeatures = [
  'ABS',
  'Keyless Entry',
  'Power Mirrors',
  'Air Bags',
  'Air Conditioning',
  'Power Windows',
  'Alloy Rims',
  'AM/FM Radio',
  'Power Locks',
  'Power Steering',
  'Immobilizer Key',
  'CD Player',
];

final List<String> sparePartsCategories = [
  'Body Parts',
  'Crush plant',
  'Hydraulic pump',
  'Cabin',
  'Hydraulic Jack',
  'Excavator',
  'Engine',
  'Loader Bucket',
  'Boozer Compressor',
];
